### ISSUE TITLE
Getting Unauthorized access

### ISSUE THREAD

**Issue by dib0** [gilesmartin/blinkcontrol#1]
Hi!

Just starting to tinker around with my Blink system (I received it last Thursday). I see you've recently changed some of the scripts. Do these still work for you? The login seems to work with me and return an auth code. But all the other calls return "{"message":"Unauthorized Access"}".

If the scripts does work on your end, then I'm doing something wrong. Otherwise maybe the API has changed.

Thanks for the script, anyway :-) I am tryhing to use it to auto arm/disarm the Blink camera's when not home/home. It would be cool to have this working.

**Comment by gilesmartin** [comment]
The scripts are still working for me. Just to test I deleted the contents of ~/.blinkcontrol and ran bcsetup again. After grabbing a new auth code I was able to arm and disarm using blinkcontrol arm and blinkcontrol disarm. 

Can you post the commands you are running and the output? What is your current system?

**Comment by dib0** [comment]
If I run ./blinkcontrol status (don't have it installed in the /usr/local/bin yet) I get no result.

Starting with the authorization test:
curl -s -H "Host: prod.immedcat ia-semi.com" -H "TOKEN_AUTH: $authcode" --compressed https://prod.immedia-semi.com/homescreen
returns:
{"message":"Unauthorized Access"}

Then it retreives a new authcode (which works fine):
running curl -s -H "Host: prod.immedia-semi.com" -H "Content-Type: application/json" --data-binary '{ "password" : "mypassword", "client_specifier" : "iPhone 9.2 | 2.2 | 222", "email" : "me@me.coml" }' --compressed https://prod.immedia-semi.com/login
Returns a network ID and authcode etc.

If I perform the command to ARM the network:
 curl -s -H "Host: prod.immedia-semi.com" -H "TOKEN_AUTH: mytoken" --data-binary "" --compressed https://prod.immedia-semi.com/network/my nw id/arm
Then I get the following response:
{"message":"Unauthorized Access"}

With different tries, I still don't have it working :-$... I'm trying to have a look at the inner workings of the app, but until now I only can conclude that you did it like the API should work.

**Comment by dib0** [comment]
I currently run this from My rapsberry pi model 2b

**Comment by gilesmartin** [comment]
hmm...that is quite odd. If you are running the commands directly it should definitely work. I am using the unofficial blinkmonitor protocol from:

https://github.com/MattTW/BlinkMonitorProtocol

your arm command looks correct according to that site. It should be:

curl -H "Host: prod.immedia-semi.com" -H "TOKEN_AUTH: authtoken from login" --data-binary "" --compressed https://prod.immedia-semi.com/network/*network_id_from_networks_call*/arm

maybe try running curl with the -v option (curl -v -H "Host: prod.immedia-semi.com" -H "TOKEN_AUTH: authtoken from login" --data-binary "" --compressed https://prod.immedia-semi.com/network/*network_id_from_networks_call*/arm) to see what it is sending to the server?

**Comment by dib0** [comment]
I used -v for the networks command, but there's nothing unusual in the output:
- About to connect() to prod.immedia-semi.com port 443 (#0)
-   Trying 52.1.40.163...
- connected
- Connected to prod.immedia-semi.com (52.1.40.163) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: none
  CApath: /etc/ssl/certs
- SSLv3, TLS handshake, Client hello (1):
- SSLv3, TLS handshake, Server hello (2):
- SSLv3, TLS handshake, CERT (11):
- SSLv3, TLS handshake, Server key exchange (12):
- SSLv3, TLS handshake, Server finished (14):
- SSLv3, TLS handshake, Client key exchange (16):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSL connection using ECDHE-RSA-AES128-GCM-SHA256
- Server certificate:
-        subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.prod.immedia-semi.com
-        start date: 2015-09-24 00:00:00 GMT
-        expire date: 2016-09-23 23:59:59 GMT
-        subjectAltName: prod.immedia-semi.com matched
-        issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
-        SSL certificate verify ok.
  > GET /networks HTTP/1.1
  > User-Agent: curl/7.26.0
  > Accept: _/_
  > Accept-Encoding: deflate, gzip
  > Host: prod.immedia-semi.com
  > TOKEN_AUTH: myauthcode
  > 
- additional stuff not fine transfer.c:1037: 0 0
- HTTP 1.1 or later with persistent connection, pipelining supported
  < HTTP/1.1 401 Unauthorized
  < Blink-Served-By: i-379f63cf
  < Content-Type: application/json
  < Date: Sun, 22 May 2016 14:39:13 GMT
  < Server: nginx/1.9.7 + Phusion Passenger 5.0.23
  < Status: 401 Unauthorized
  < X-Content-Type-Options: nosniff
  < X-Powered-By: Phusion Passenger 5.0.20
  < Content-Length: 33
  < Connection: keep-alive
  < 
- Connection #0 to host prod.immedia-semi.com left intact
  {"message":"Unauthorized Access"}\* Closing connection #0
- SSLv3, TLS alert, Client hello (1):

The strange thing is that if it works for you, the problem should be on my end.

**Comment by gilesmartin** [comment]
my only thought is that you might be copying only part of the auth code. it sometimes comes across with a dash "-" in the middle. You need to grab the whole portion including the dash and not including the quotation mark following the code.

**Comment by dib0** [comment]
Ok, Thanks. I'm rebuilding it using PHP, but with the same results there.

**Comment by dullage** [comment]
Just as a useful note for anyone else who searches for this issue. I managed to solve this by changing the host I use for the API calls (apart from the login): https://rest-prde.immedia-semi.com.

I'm not sure of the detail behind it but it worked for me and might be useful to someone else.
